[package]
name = "gridio"
version = "1.0.4"
edition = "2021"

[lib]
name = "gridio"
crate-type = ["cdylib"]

[dependencies]
numpy = "0.27.0"
pyo3 = { version = "0.27", features = ["extension-module"] }
textgrid = { path = "./textgrid" }
